env:
  browser: true
  es2021: true
extends:
  - standard
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  semi:
    - 2
    - always
  quotes:
    - 2
    - double
  no-unused-vars:
    - 2
    - argsIgnorePattern: "^_"
      vars: all
      args: after-used
